### ISSUE TITLE
Join the team (post here to be added to the nf-core team)

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-core.github.io#1]
Please add a comment below if you would like to be added to the nf-core community.. Everyone is welcome!

> _**Note:** After you post here, we will email you an invitation through github to join the bioconda team. Click the link in that invitation in order to be added._

ps. I totally stole this idea (and many others) from [bioconda](https://bioconda.github.io/index.html).. Thanks guys!

**Comment by tdelhomme** [comment]
:+1:

**Comment by ewels** [comment]
Hi @tdelhomme - welcome! I've just added you to the organisation.

**Comment by ewels** [comment]
ps. Come and chat in https://gitter.im/nf-core/Lobby if you're curious about how to get involved...

**Comment by tdelhomme** [comment]
@ewels thanks for the add! will join the gitter chat :+1:

**Comment by mfoll** [comment]
👍

**Comment by marchoeppner** [comment]
<-

**Comment by vsmalladi** [comment]
I will like to be added

**Comment by ewels** [comment]
Moved to https://github.com/nf-core/nf-co.re/issues/3
