### ISSUE TITLE
Error.md not rendered on website

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-core.github.io#17]
The error.md file is not rendered on any of the webpages.

(or I am just to stupid to find it...)

**Comment by ewels** [comment]
It’s not currently linked to anywhere, as my thinking was that people would only go there from the error messages that are shown from lint tests. I guess it could be useful to link to though.. It’s at https://nf-core.github.io/errors

**Comment by sven1103** [comment]
my browsing would be sth like nf-core.github.io -> Docs -> Guidelines -> Linting -> Error Codes

**Comment by sven1103** [comment]
Additionally, one could also print the URL to the error codes on the command line, when the tests are done.

**Comment by ewels** [comment]
The URL is already printed on the command line when the tests are done.. :)

**Comment by ewels** [comment]
At least, when they fail - see https://travis-ci.org/ewels/nf-core-methylseq/jobs/352435293#L637 for an example:

```
=================
 LINTING RESULTS
=================
  31 tests passed
   0 tests had warnings
   3 tests failed
FAILURES:
  https://nf-core.github.io/errors#4: Config variable not found: version
  https://nf-core.github.io/errors#4: Config variable not found: nf_required_version
  https://nf-core.github.io/errors#5: Continuous integration does not check minimum NF version: '/home/travis/build/ewels/nf-core-methylseq/.travis.yml'
```

**Comment by sven1103** [comment]
That happens when you just do tests for the test suite. You just have no clue, what the real implementation looks like ...

**Comment by ewels** [comment]
Link added to the errors page from the docs >> https://github.com/nf-core/nf-core.github.io/pull/18
