### ISSUE TITLE
Handle draft and pre-releases

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-core.github.io#20]
Currently, we just look for any release, and show the latest. We should probably filter out draft releases though, and perhaps pre-releases.

**Comment by sven1103** [comment]
I think we should keep it simple, so people don't get confused. Once your pipeline is out of development, it is released. Once you implemented new features, and they work, publish a new release. Done.

**Comment by ewels** [comment]
Agreed, but doesn't mean that the website code can't filter these out if they do occur :)

Already fixed in #21
