### ISSUE TITLE
Clicking on the stargazer icon calls the GitHub API instead of showing the stars

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-core.github.io#22]
When you click on the star icon next to the repo name, an API call is made and the result (the return itself) unfiltered shown to the user.

Expected behaviour: Show the stargazers

Actual behaviour: API call

**Comment by ewels** [comment]
hah, oops! Sorry, not sure how that one slipped through..

**Comment by sven1103** [comment]
all good, all good. It slipped through the review process :D I was just clicking around (real life tests!)
