### ISSUE TITLE
CRAM format requirement

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/nf-core.github.io#29]
Hi,

the CRAM format has been around for some time, but still isn't used all that much in bioinformatics. There are some valid reasons for that - but mostly I think this has to do with tool chains having taken some time to be fully cram compatible. As far as I can see, this is now (mostly) the case. 

So my suggestion would be to require pipelines to have, at minimum, a switch statement that allows users to write outputs as either cram or bam, with cram being the default. The storage savings alone are pretty significant (40-50%).

Something like `--bam true` would probably be sufficient? 

What are possible concerns?
- Reading cram takes more CPU cycles due to the higher compression level (?)
- Writing cram requires a reference fasta (which is not an issue in our use case, since there is a reference anyway)
- Resistance towards change by users (hence the bam switch statement)

What are possible benefits:
- 50% savings on storage for large-scale sequencing providers and compute clusters
- faster transfer times (again, big plus for data providers...)

Cheers,
Marc

**Comment by apeltzer** [comment]
Agreed - lets make this happen. Been planning this for one of my pipelines already for quite a while, the updated one will have that anyways and GATK/Picard/Samtools are supporting it widely. HTSlib based third-party applications automatically have support for reading/writing CRAM, too.

**Comment by sven1103** [comment]
:+1:
