### ISSUE TITLE
Website: List nf-core pipelines

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-core.github.io#4]
> _[Phil edit:]_
> The website should automatically list all nf-core pipelines in the organisation. These should be in a list with standardised flags (maybe a table?). It should be possible to sort / filter by these flags.

These flags can for example be:

- out-of-date
- dead
- activity flags based on the number of commits? (A lively repository is probably a hint for a good workflow)
- star based ranking?

**Comment by ewels** [comment]
I think we can automatically pull the dates for the last release, first + most recent commit dates (for age), number of commits and number of GitHub stars etc for each pipeline dynamically using the GitHub API. Then we can just put all of these numbers into a table on the website on page load.

The only one which is trickier is the `dead` flag. Though perhaps we can archive repositories like this and also pull that status? I'm not sure when we'd ever want to do this though.

**Comment by sven1103** [comment]
> I think we can automatically pull the dates for the last release, first + most recent commit dates (for age), number of commits and number of GitHub stars etc for each pipeline dynamically using the GitHub API. 

Yes, I think using information we can get via the GitHub API makes things way easier.

> The only one which is trickier is the dead flag. Though perhaps we can archive repositories like this and also pull that status?

Maybe `dead` or `orphaned` is determined by the user via the age flag automatically...

**Comment by ewels** [comment]
I updated the title and your first issue a little, hope that's ok!

**Comment by andreas-wilm** [comment]
This might be the wrong place but does it make sense to list a main contact person per pipeline? Or would this change too quickly and thus becomes unmaintainable?

**Comment by ewels** [comment]
Yeah, that was discussed on another issue somewhere. I think it would be a good idea - or perhaps at least a list of the primary maintainers / contributors. I’m guessing that most pipelines will have one or two people behind most of their code (and it can always change).
