### ISSUE TITLE
Registration confirmation of applying workflows

### ISSUE THREAD

**Issue by sven1103** [nf-core/nf-core.github.io#5]
One could use the nf-core tools to perform an integrity check. This one must pass, otherwise your WF will not be registered?

**Comment by ewels** [comment]
I'm not sure about this one.. In my head the test would run on travis, which itself would only run on GitHub PRs / changes etc. So by definition the person must be registered.

We do need to think about how to bring new pipelines in to the org though. I guess to start with it'll be a case of just talking to people and manual checks. Not sure if there's a more rigorous way to handle this.

**Comment by sven1103** [comment]
> I'm not sure about this one.. In my head the test would run on travis, which itself would only run on GitHub PRs / changes etc. So by definition the person must be registered.

So you will manually check, if a WF fulfils the requirements? We have no control about the travis scripts running on third party Git repos. Or do I get something totally wrong here? 

> We do need to think about how to bring new pipelines in to the org though. I guess to start with it'll be a case of just talking to people and manual checks. Not sure if there's a more rigorous way to handle this.

I think for the beginning it might be enough. In the future, one might have a simple registration "form" to hook up WF repos.

Do you have a particular framework in mind for displaying all the registered WFs? Like Flask?

**Comment by ewels** [comment]
> So you will manually check, if a WF fulfils the requirements? We have no control about the travis scripts running on third party Git repos. Or do I get something totally wrong here?

Assuming that the travis script in the pipeline repo calls the `nf-core` linting package then a fail there will show up on the PR and block a merge. Maybe I misunderstood your original issue though - I think I was maybe thrown by _Registration confirmation_ in the title and thought that you meant that `nf-core` should check that there is a registered github account or something. If you just mean that the `nf-core` linting must pass then yes, I agree with this issue! :)

> I think for the beginning it might be enough. In the future, one might have a simple registration "form" to hook up WF repos.

Yes, let's add that one to the "think about it when it becomes a problem" list..

> Do you have a particular framework in mind for displaying all the registered WFs? Like Flask?

At the moment the website is built using Jekyll running on the GitHub pages framework. I quite like this as it's super simple and trivial to edit the markdown files. I'm not sure that we need to run anything complicated enough to require Flask. We can have a simple JavaScript file that talks to the GitHub repository to pull a list of the repositories and stats pretty easily I think.

For example, simply a case of pulling JSON from https://api.github.com/orgs/nf-core/repos

```json
[
  {
    "id": 114909219,
    "name": "cookiecutter",
    "full_name": "nf-core/cookiecutter",
    "owner": {
      "login": "nf-core",
      "id": 35520196,
      "avatar_url": "https://avatars0.githubusercontent.com/u/35520196?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nf-core",
      "html_url": "https://github.com/nf-core",
      "followers_url": "https://api.github.com/users/nf-core/followers",
      "following_url": "https://api.github.com/users/nf-core/following{/other_user}",
      "gists_url": "https://api.github.com/users/nf-core/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nf-core/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nf-core/subscriptions",
      "organizations_url": "https://api.github.com/users/nf-core/orgs",
      "repos_url": "https://api.github.com/users/nf-core/repos",
      "events_url": "https://api.github.com/users/nf-core/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nf-core/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/nf-core/cookiecutter",
    "description": "Template for your own top-end Nextflow pipeline, customised using Cookiecutter",
    "fork": true,
    "url": "https://api.github.com/repos/nf-core/cookiecutter",
    "forks_url": "https://api.github.com/repos/nf-core/cookiecutter/forks",
    "keys_url": "https://api.github.com/repos/nf-core/cookiecutter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/nf-core/cookiecutter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/nf-core/cookiecutter/teams",
    "hooks_url": "https://api.github.com/repos/nf-core/cookiecutter/hooks",
    "issue_events_url": "https://api.github.com/repos/nf-core/cookiecutter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/nf-core/cookiecutter/events",
    "assignees_url": "https://api.github.com/repos/nf-core/cookiecutter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/nf-core/cookiecutter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/nf-core/cookiecutter/tags",
    "blobs_url": "https://api.github.com/repos/nf-core/cookiecutter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/nf-core/cookiecutter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/nf-core/cookiecutter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/nf-core/cookiecutter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/nf-core/cookiecutter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/nf-core/cookiecutter/languages",
    "stargazers_url": "https://api.github.com/repos/nf-core/cookiecutter/stargazers",
    "contributors_url": "https://api.github.com/repos/nf-core/cookiecutter/contributors",
    "subscribers_url": "https://api.github.com/repos/nf-core/cookiecutter/subscribers",
    "subscription_url": "https://api.github.com/repos/nf-core/cookiecutter/subscription",
    "commits_url": "https://api.github.com/repos/nf-core/cookiecutter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/nf-core/cookiecutter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/nf-core/cookiecutter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/nf-core/cookiecutter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/nf-core/cookiecutter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/nf-core/cookiecutter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/nf-core/cookiecutter/merges",
    "archive_url": "https://api.github.com/repos/nf-core/cookiecutter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/nf-core/cookiecutter/downloads",
    "issues_url": "https://api.github.com/repos/nf-core/cookiecutter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/nf-core/cookiecutter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/nf-core/cookiecutter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/nf-core/cookiecutter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/nf-core/cookiecutter/labels{/name}",
    "releases_url": "https://api.github.com/repos/nf-core/cookiecutter/releases{/id}",
    "deployments_url": "https://api.github.com/repos/nf-core/cookiecutter/deployments",
    "created_at": "2017-12-20T16:37:53Z",
    "updated_at": "2018-02-14T09:23:15Z",
    "pushed_at": "2018-02-12T23:35:12Z",
    "git_url": "git://github.com/nf-core/cookiecutter.git",
    "ssh_url": "git@github.com:nf-core/cookiecutter.git",
    "clone_url": "https://github.com/nf-core/cookiecutter.git",
    "svn_url": "https://github.com/nf-core/cookiecutter",
    "homepage": "",
    "size": 34,
    "stargazers_count": 14,
    "watchers_count": 14,
    "language": "Groovy",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 1,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit"
    },
    "forks": 0,
    "open_issues": 1,
    "watchers": 14,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  },
```
_(truncated..)

Can then just have a hardcoded blacklist of repositories to ignore (eg. `tools`, `cookiecutter`, `nf-core.github.io`).

**Comment by sven1103** [comment]
> Assuming that the travis script in the pipeline repo calls the nf-core linting package then a fail there will show up on the PR and block a merge. Maybe I misunderstood your original issue though - I think I was maybe thrown by Registration confirmation in the title and thought that you meant that nf-core should check that there is a registered github account or something. If you just mean that the nf-core linting must pass then yes, I agree with this issue! :)

Sorry, the title was misleading. I meant what you just mentioned.

> At the moment the website is built using Jekyll running on the GitHub pages framework. I quite like this as it's super simple and trivial to edit the markdown files. I'm not sure that we need to run anything complicated enough to require Flask. We can have a simple JavaScript file that talks to the GitHub repository to pull a list of the repositories and stats pretty easily I think.

No, Jekyll is fine! Just don't have experience with it, but using simple JavaScript for the API calls should be fine.

I think we can close this issue, since you added the requirement for the 'lint test parsing' :)

**Comment by ewels** [comment]
> No, Jekyll is fine! Just don't have experience with it

Jekyll is nice! The GitHub pages variant especially, as you don't even need all the theme stuff, only the things that you want to overwrite (the basic site is just a single markdown file and a small config). Instructions for running locally here if you want to play: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
